# Generated by Django 5.0.1 on 2024-01-20 01:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactManagementApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=150)),
                ('phone_number', models.CharField(max_length=11)),
                ('email', models.CharField(max_length=25)),
                ('address', models.CharField(max_length=150)),
                ('userEmail', models.CharField(max_length=25)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contactManagementApp.user')),
            ],
        ),
    ]
