# Generated by Django 5.0.1 on 2024-01-20 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactManagementApp', '0002_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='userEmail',
            field=models.CharField(max_length=50),
        ),
    ]
